language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

notifications:
  email: false

install: "pip install beautifulsoup4 lxml nose-timer"

script: nosetests -v --with-timer
